require: rubocop-rspec

AllCops:
  Exclude:
    - vendor/**/*
    - bin/**
    - config/environments/**
  SuggestExtensions: false
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context', 'let', 'include_context']

RSpec/MultipleMemoizedHelpers:
  Enabled: false
