require: rubocop-rspec

AllCops:
  Exclude:
    - .bundle/**
    - vendor/**/*
    - bin/**
    - Guardfile
    - config/environments/**

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'let']
