kind: Service
apiVersion: v1
metadata:
  name: "fb-pdf-generator-api-svc-{{ .Values.environmentName }}"
  labels:
    app: "fb-pdf-generator-api-{{ .Values.environmentName }}"
    appGroup: "fb-pdf-generator"
spec:
  ports:
  - port: 3000
    name: http
    targetPort: 3000
  selector:
    app: "fb-pdf-generator-api-{{ .Values.environmentName }}"
