apiVersion: v1
kind: ConfigMap
metadata:
  name: fb-pdf-generator-api-env-{{ .Values.environmentName }}
  namespace: formbuilder-platform-{{ .Values.environmentName }}
data:
  RAILS_ENV: "production"
  MAX_IAT_SKEW_SECONDS: "60"
  SERVICE_TOKEN_CACHE_ROOT_URL: "http://fb-service-token-cache-svc-{{ .Values.environmentName }}/"
  RAILS_LOG_TO_STDOUT: "true"
