apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-submitter-to-access-pdf-generator
  namespace: formbuilder-platform-{{ .Values.environmentName }}
spec:
  podSelector:
    matchLabels:
      app: fb-pdf-generator-api-{{ .Values.environmentName }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: formbuilder-platform-{{ .Values.environmentName }}
    - podSelector:
        matchLabels:
          appGroup: fb-submitter
    ports:
    - protocol: TCP
      port: 3000
